# Generated by Django 3.2.3 on 2022-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('salary', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
